# Generated by Django 5.1.3 on 2026-01-30 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0002_chatmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Reason for rejection by doctor", null=True
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="requested_by_admin",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who requested this appointment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("pending_approval", "Pending Approval"),
                    ("scheduled", "Scheduled"),
                    ("confirmed", "Confirmed"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                    ("no_show", "No Show"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
