# Generated by Django 5.0.1 on 2026-02-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0003_appointment_rejection_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="khalti_transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Khalti transaction ID for verification",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="payment_status",
            field=models.BooleanField(
                default=False,
                help_text="Whether the patient has paid the registration fee",
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="registration_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=500.0,
                help_text="Registration fee amount in NPR",
                max_digits=10,
            ),
        ),
    ]
