# Generated by Django 5.0.1 on 2026-02-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0004_patientprofile_khalti_transaction_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="requested_by_admin",
            new_name="requested_by",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="consultation_fee",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="payment_status",
        ),
        migrations.AddField(
            model_name="appointment",
            name="call_duration",
            field=models.PositiveIntegerField(
                default=0, help_text="Call duration in seconds"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor_token",
            field=models.CharField(
                blank=True,
                help_text="Secure token for doctor to join video call",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient_token",
            field=models.CharField(
                blank=True,
                help_text="Secure token for patient to join video call",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="recording_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether call recording is enabled (requires patient consent)",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="screen_sharing_active",
            field=models.BooleanField(
                default=False, help_text="Whether screen sharing is currently active"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="token_created_at",
            field=models.DateTimeField(
                blank=True, help_text="When the tokens were generated", null=True
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="video_call_ended_at",
            field=models.DateTimeField(
                blank=True, help_text="When the video call ended", null=True
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="video_call_room_id",
            field=models.CharField(
                blank=True,
                help_text="Unique room ID for video call",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="video_call_started_at",
            field=models.DateTimeField(
                blank=True, help_text="When the video call started", null=True
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="video_call_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("waiting", "Waiting for Doctor"),
                    ("in_progress", "In Progress"),
                    ("ended", "Ended"),
                ],
                default="not_started",
                help_text="Current status of the video call",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("pending_approval", "Pending Approval"),
                    ("scheduled", "Scheduled"),
                    ("confirmed", "Confirmed"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="khalti_transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Khalti transaction reference",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="payment_status",
            field=models.BooleanField(
                default=False, help_text="Whether patient has paid registration fee"
            ),
        ),
    ]
