# Generated by Django 5.0.1 on 2026-02-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0005_rename_requested_by_admin_appointment_requested_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorprofile",
            name="consultation_fee",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="website",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="registration_fee",
        ),
        migrations.AddField(
            model_name="hospital",
            name="appointment_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=1000.0,
                help_text="Fee per appointment in NPR",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="payment_status",
            field=models.BooleanField(
                default=False, help_text="Whether patient has paid for appointments"
            ),
        ),
    ]
