# Generated by Django 5.0.1 on 2026-02-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0006_remove_doctorprofile_consultation_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="doctor_profiles/"
            ),
        ),
    ]
