# Generated by Django 5.0.1 on 2026-02-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0007_doctorprofile_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="doctor_token",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="patient_token",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="token_created_at",
        ),
    ]
