# Generated by Django 5.0.1 on 2026-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0008_remove_appointment_doctor_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="chat_attachments/%Y/%m/%d/"
            ),
        ),
    ]
