"""
Django settings for telemedicine project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import importlib.util
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-$ebz__l=q!8x@$jv6mxur&(gyx$ndlud_prd2n#gybro)rrie-")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")



# Application definition

INSTALLED_APPS = [
    # Use Daphne's ASGI runserver automatically when installed.
    *(["daphne"] if importlib.util.find_spec("daphne") else []),
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",  # Django Channels for WebSocket support
    "corsheaders",  # CORS headers for WebRTC
    "accounts",
    "medical",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.decorators.DisableClientSideCachingMiddleware",  # Disable caching for real-time updates
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]




ROOT_URLCONF = "telemedicine.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI and ASGI applications
WSGI_APPLICATION = "telemedicine.wsgi.application"
ASGI_APPLICATION = "telemedicine.asgi.application"  # Django Channels ASGI


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")
DB_CONN_MAX_AGE = int(os.environ.get("DB_CONN_MAX_AGE", "600"))
DB_CONNECT_TIMEOUT = int(os.environ.get("DB_CONNECT_TIMEOUT", "10"))

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=DB_CONN_MAX_AGE,
            conn_health_checks=True,
            ssl_require=not DEBUG,
        )
    }
    DATABASES["default"].setdefault("OPTIONS", {})
    DATABASES["default"]["OPTIONS"]["connect_timeout"] = DB_CONNECT_TIMEOUT
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kathmandu"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (User uploads)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# WhiteNoise configuration with compression for static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Cache control headers - DISABLED page caching to prevent stale data issues
# Page caching middleware removed to ensure real-time updates for notifications
# CACHE_MIDDLEWARE_SECONDS = 600  # DISABLED - was causing stale page issues
# CACHE_MIDDLEWARE_KEY_PREFIX = "telemedicine"  # DISABLED

# Security headers
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Disable browser caching for dynamic content to ensure real-time updates
# This prevents stale pages and ensures notifications appear immediately
CACHE_CONTROL_MAX_AGE = 0
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


# CSRF trusted origins for Defang deployment
CSRF_TRUSTED_ORIGINS = [
    "https://*.defang.dev",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = "accounts.User"

# Khalti Payment Gateway Configuration (ePayment API v2)
KHALTI_PUBLIC_KEY = os.environ.get("KHALTI_PUBLIC_KEY", "117e2f1f48d84b52a47ef8fdf4623f5f")
KHALTI_SECRET_KEY = os.environ.get("KHALTI_SECRET_KEY", "1753221752054f0bbed8c345b7dd6b65")
# Use test environment for now
KHALTI_GATEWAY_URL = "https://a.khalti.com/api/v2/epayment/initiate/"
KHALTI_VERIFY_URL = "https://a.khalti.com/api/v2/epayment/lookup/"



# Django Channels Configuration
REDIS_URL = os.environ.get("REDIS_URL")

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    # Local development fallback when Redis is not running.
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }

# Redis Caching Configuration (CRITICAL FOR PERFORMANCE)
# This significantly improves page load times by caching queries and sessions
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "CONNECTION_POOL_KWARGS": {
                    "max_connections": 50,
                    "retry_on_timeout": True,
                },
                "SOCKET_CONNECT_TIMEOUT": 5,
                "SOCKET_TIMEOUT": 5,
                "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            },
            "KEY_PREFIX": "telemedicine",
            "TIMEOUT": 300,  # 5 minutes default cache timeout
        }
    }
    # Use Redis for sessions (faster than database)
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
else:
    # Fallback to in-memory cache for development
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
            "OPTIONS": {
                "MAX_ENTRIES": 10000,
            }
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.db"

# CORS Configuration for WebRTC

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://*.defang.dev",
]

CORS_ALLOW_CREDENTIALS = True

# WebRTC Configuration
WEBRTC_STUN_SERVERS = [
    "stun:stun.l.google.com:19302",
    "stun:stun1.l.google.com:19302",
]

# TURN server configuration (for production, use your own TURN server)
WEBRTC_TURN_SERVERS = [
    {
        "urls": os.environ.get("TURN_SERVER_URL", "turn:turn.example.com:3478"),
        "username": os.environ.get("TURN_USERNAME", "user"),
        "credential": os.environ.get("TURN_CREDENTIAL", "pass"),
    }
]

# Video Call Settings
VIDEO_CALL_MAX_DURATION = 60  # minutes
VIDEO_CALL_DEFAULT_FEE = 500.00  # NPR
VIDEO_CALL_TOKEN_EXPIRY = 24  # hours
