# Generated by Django 5.1.3 on 2026-01-30 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("medical", "0002_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff",
                to="medical.hospital",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("doctor", "Doctor"),
                    ("admin", "Hospital Admin"),
                    ("super_admin", "Super Admin"),
                ],
                default="patient",
                max_length=20,
            ),
        ),
    ]
